/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stack_QueuePackege;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Stack_QueuePackege.App classUnderTest = new Stack_QueuePackege.App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testEnQueue(){
        Animal animal = new Animal("cat");
        animal.enqueue(animal.getKind());
        assertEquals("cat",animal.getKind());
    }
    @Test public void testdeQueue(){
        Animal animal = new Animal("dog");
        assertEquals(" the pref was a dog",animal.deQueue("dog"));
    }
}
