package Stack_QueuePackege;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import Nodes.Node;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
Stack stack = new Stack();
Queue queue = new Queue();
//        stack.push(5);
//        stack.push(4);
//        stack.push(3);
//        stack.push(2);
//        stack.push(1);
//        stack.push(0);
//        stack.pop();
//        stack.pop();
//        stack.peek();
//        System.out.println("this on the Top --> "+stack.peek());
//        stack.tostring();
//
//        queue.enQueue(5);
//        queue.enQueue(4);
//        queue.enQueue(3);
//        queue.enQueue(2);
//        queue.enQueue(1);
//        queue.enQueue(0);
//        queue.dequeue();
//        System.out.println("this is the front --> "+queue.getFront());
//        queue.tostring();

//PseudoQueue test = new PseudoQueue();

//test.push(1);
//test.push(2);
//test.push(3);
//test.push(3);
//test.enqueue(1);
//test.enqueue(2);
//test.enqueue(3);
//test.enqueue(4);
//test.dequeue();
//test.dequeue();// {1} has been removed
//      test.tostring();
     Animal animal = new Animal("cat");
     Animal animal1 = new Animal("dog");
     Animal animal2 = new Animal("monkey");
     animal.enqueue(animal.getKind());
     animal.enqueue(animal1.getKind());
     animal.enqueue(animal2.getKind());
     System.out.println( animal.deQueue("dog"));
     animal.tostring();

    }
}
