/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DuckDuckGoose;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
//      int k =3;
//char[] Players= new char[5];
//        Players = new char[]{'A', 'B', 'C', 'D', 'E'};
//     DuckDuckGoose test = new DuckDuckGoose();
//     test.duckDuckGoose(Players,k);
//        System.out.println(test.duckDuckGoose(q,k));
    }
}
