/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedListSourcePackege;
import LinkedListSourcePackege.types.LinkedList;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static final LinkedList<Integer> list = new LinkedList<>();
    public static void main(String[] args) {
        System.out.println("Type of linked list is integer");
list.insert(96);
        list.insert(20);
        list.insert(18);
        System.out.println( "Does this number exisest?"+ list.includes(18));
        System.out.println("Does this number exisest?"+ list.includes(9));
list.append(22);
list.inserBefore(20,300);
list.inserAfter(20,500);
        System.out.println(list.tostringg());
    }
}