/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.Test;
import types.LinkedList;

import static org.junit.Assert.*;

public class AppTest {

    private LinkedList<String> list;

    @Test public void testLinkedListTrue(){
        list=new LinkedList<>();
        list.add("mahmood");
        list.insert("alashqar");
        assertEquals(true, list.includes("mahmood"));
    }

    @Test public void testLinkedListFalse(){
        list=new LinkedList<>();
        list.add("abd");
        list.insert("alashqar");
        assertEquals(false, list.includes("mahmood"));
    }

    @Test public void testLinkedListToString(){
        list = new LinkedList<>();
        list.add("mahmood");
        list.add("Yousef");
        list.insert("alashqar");
        assertEquals("{mahmood}-> {yousef}-> {alashqar}-> NULL", list.toString());
    }
}
